config/routes.rb
Rails.application.routes.draw do
   root 'index#index'
   
   get '/search/', to: 'search#index', as: 'search'
   
   get '/post', to: 'post#index', as: 'posts'
   post '/post', to: 'post#create'
   get '/post/:id', to: 'post#show', as: 'show_post'
   delete '/post/:id', to: 'post#destroy', as: 'destroy_post'
   
   get '/tag', to: 'tag#index', as: 'tags'
   post '/tag', to: 'tag#create'
   delete '/tag/:id', to: 'tag#destroy', as: 'destroy_tag'
   
   get '/foodstuff', to: 'foodstuff#index', as: 'foodstuffs'
   post '/foodstuff', to: 'foodstuff#create'
   delete '/foodstuff/:id', to: 'foodstuff#destroy', as: 'destroy_foodstuff'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/foodstuff.rb
# == Schema Information
#
# Table name: foodstuffs
#
#  id   :bigint(8)        not null, primary key
#  name :string(255)      not null
#

class Foodstuff < ApplicationRecord
  has_many :post
  has_many :post_foodstuffs, dependent: :delete_all
  has_many :post, :through => :post_foodstuffs
  auto_strip_attributes :name, strip_double_byte_space: true
  validates :name, presence: true, uniqueness: true
end

app/models/foodstuff_amount.rb
# == Schema Information
#
# Table name: foodstuff_amounts
#
#  id         :bigint(8)        not null, primary key
#  foodstuff  :string(255)      not null
#  amount     :string(255)      not null
#  order      :integer          not null
#  post_id    :bigint(8)        not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class FoodstuffAmount < ApplicationRecord
  belongs_to :post, dependent: :delete
  validates :foodstuff, presence: true, length: { maximum: 75 }
  validates :amount, presence: true, length: { maximum: 75 }
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint(8)        not null, primary key
#  name        :string(255)
#  description :text(65535)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  image       :string(255)
#

class Post < ApplicationRecord
  has_many :recipe_processes, dependent: :destroy
  has_many :foodstuff_amounts, dependent: :destroy
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :post_foodstuffs, dependent: :destroy
  has_many :foodstuffs, through: :post_foodstuffs
  accepts_nested_attributes_for :recipe_processes, allow_destroy: true
  accepts_nested_attributes_for :foodstuff_amounts, allow_destroy: true
  accepts_nested_attributes_for :post_tags, :post_foodstuffs, allow_destroy: true
  mount_uploader :image, PostImageUploader
  validates :name, presence: true, length: { maximum: 75 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :image, presence: true
  validates :recipe_processes, :length => { :minimum => 1}
end

app/models/post_foodstuff.rb
# == Schema Information
#
# Table name: post_foodstuffs
#
#  id           :bigint(8)        not null, primary key
#  post_id      :bigint(8)
#  foodstuff_id :bigint(8)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class PostFoodstuff < ApplicationRecord
  belongs_to :post
  belongs_to :foodstuff
end

app/models/post_tag.rb
# == Schema Information
#
# Table name: post_tags
#
#  id         :bigint(8)        not null, primary key
#  post_id    :bigint(8)
#  tag_id     :bigint(8)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/recipe_process.rb
# == Schema Information
#
# Table name: recipe_processes
#
#  id          :bigint(8)        not null, primary key
#  title       :string(255)
#  description :text(65535)      not null
#  order       :integer          not null
#  post_id     :bigint(8)        not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class RecipeProcess < ApplicationRecord
  belongs_to :post, dependent: :delete
  validates :title, presence: true, length: { maximum: 75 }
  validates :description, presence: true, length: { maximum: 255 }
end

app/models/tag.rb
# == Schema Information
#
# Table name: tags
#
#  id   :bigint(8)        not null, primary key
#  name :string(255)      not null
#

class Tag < ApplicationRecord
  has_many :post_tags, dependent: :delete_all
  has_many :post, through: :post_tags
  auto_strip_attributes :name, strip_double_byte_space: true
  validates :name, presence: true, uniqueness: true#, format: {with: /\A^[ぁ-んァ-ン一-龥]\z/}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/foodstuff_controller.rb
class FoodstuffController < ApplicationController
  def index
    @foodstuff = Foodstuff.new
    @foodstuffs = Foodstuff.order('id DESC')
  end
  
  def create
    @foodstuff = Foodstuff.new(foodstuff_params)
    if @foodstuff.save
      redirect_to foodstuffs_path, flash: {notice: '作成されました'}
    else
      redirect_to foodstuffs_path, flash: {error: 'エラーもしくは重複があります'}
    end
  end
  
  def destroy
    @foodstuff = Foodstuff.find_by(id: params[:id])
    @foodstuff.destroy
    redirect_to foodstuffs_path, flash: {notice: '削除されました'}
  end
  
  private
  def foodstuff_params
    params.require(:foodstuff).permit(:name)
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
   
   def index
     @post = Post.limit(10).order('created_at DESC')
     @q = Post.search
   end
end

app/controllers/post_controller.rb
class PostController < ApplicationController

  before_action :set_process_order, :set_foodstuff_amount_order, only: [:create]
  
  def index
    @post = Post.new
    @post.recipe_processes.build
    @post.foodstuff_amounts.build
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      foodstuff = post_params[:foodstuff_amounts_attributes]
      foodstuff.each do |k, v|
        Foodstuff.find_or_create_by(name: v[:foodstuff])
      end
      redirect_to show_post_path(@post.id), flash: {notice: '作成されました。'}
    else
      @post = Post.new(post_params)
      @post.valid?
      render action: :index
    end
  end
  
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to posts_path, flash: {notice: '削除されました'}
  end
  
  private
  def post_params
    params.require(:post).permit(
      :name,
      :description,
      :image,
      :image_cache,
      { 
        :tag_ids => [],
        :foodstuff_ids => []
      },
      foodstuff_amounts_attributes:[
        :foodstuff,
        :amount,
        :order,
      ],
      recipe_processes_attributes:[
        :title,
        :description,
        :order,
      ]
      )
  end
  
  def set_process_order
    order_num = 0
    process_order = params[:post][:recipe_processes_attributes]
    process_order.each do |k, v|
      order_num += 1
      v[:order] = order_num
    end
  end
  def set_foodstuff_amount_order
    order_num = 0
    foodstuff_amount_order = params[:post][:foodstuff_amounts_attributes]
    foodstuff_amount_order.each do |k, v|
      order_num += 1
      v[:order] = order_num
    end
  end
  
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @word = params[:q]
    @search = Post.ransack(@word)
    @posts = @search.result
    @q = Post.search
  end
end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  
  def index
    @tag = Tag.new
    @tags = Tag.order('id DESC')
  end
  
  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      redirect_to tags_path, flash: {notice: '作成されました'}
    else
      redirect_to tags_path, flash: {error: 'エラーもしくは重複があります'}
    end
  end
  
  def destroy
    @tag = Tag.find_by(id: params[:id])
    @tag.destroy
    redirect_to tags_path, flash: {notice: '削除されました'}
  end
  
  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foodstuff_helper.rb
module FoodstuffHelper
end

app/helpers/index_helper.rb
module IndexHelper
  
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/common/_check_boxes.html.erb
<div class="row">
  <%= object_name.all if object_name.nil? %>
  <%= f.collection_check_boxes(id_name, object_name, :id, :name, include_hidden: false) do |c|%>
    <div class="col s3">
      <%= c.label do %>
        <%= c.check_box(class: 'filled-in') %>
        <span><%= c.object.name %></span>
      <% end %>
    </div>
  <% end %>
</div>

app/views/common/_foodstuff_list.html.erb
<li class="mdl-list__item list-bd__bottom tag__name">
  <span class="mdl-list__item-primary-content">
    <%= data.name%>
  </span>
  <%= link_to destroy_foodstuff_path(data), :method => :delete do %>
    <%= button_tag(type: 'submit', class: 'btn-floating btn-large waves-effect waves-light red', name: nil) do%>
      <i class="material-icons">delete_sweep</i>
    <% end %>
  <% end %>
</li>

app/views/common/_new_form.html.erb
<%= form_for data, :html => { class: 'col s12 center-align' } do |d|%>
  <div class="row">
    <div class="input-field inline col s8 offset-s2">
      <%= d.text_field :name, autocomplete:'off' %>
      <%= d.label :name, "新規の#{t_name}を作成" %>
    </div>
    <%= button_tag(type: 'submit', class: 'btn-floating btn-large waves-effect waves-light indigo darken-4', form: "new_#{f_name}", name: nil) do%>
      <i class="material-icons">add</i>
    <% end %>
  </div>
<% end %>

app/views/common/_tag_list.html.erb
<li class="mdl-list__item list-bd__bottom tag__name">
  <span class="mdl-list__item-primary-content">
    <%= data.name%>
  </span>
  <%= link_to destroy_tag_path(data), :method => :delete do %>
    <%= button_tag(type: 'submit', class: 'btn-floating btn-large waves-effect waves-light red', name: nil) do%>
      <i class="material-icons">delete_sweep</i>
    <% end %>
  <% end %>
</li>

app/views/common/_title.html.erb
<div class="row">
  <div class="col s12">
    <h1 class="center-align"><%= title %></h1>
  </div>
    <h1 class="center-align"></h1>
</div>

app/views/foodstuff/index.html.erb
<div class="container">
<section>
  <%= render partial: "common/title", locals: {title: "食材作成"}%>
  <%= render partial: "common/new_form", locals: {data: @foodstuff, t_name: '食材', f_name: 'foodstuff'}%>
</section>
<% if @foodstuffs.present? %>
<section>
  <div class="row">
    <h2 class="center-align">食材一覧</h2>
  </div>
  <div class="row">
    <ul class="col s6 offset-s3">
      <%= render partial: "common/foodstuff_list", collection: @foodstuffs, as: "data" %>
    </ul>
  </div>
</section>
<% end %>
</div>

app/views/index/index.html.erb
<% content_for :javascipt do %>
  <%= javascript_include_tag "index" %>
<% end %>
<div class="container">
  <section>
    <%= render partial: "common/title", locals: {title: "レシピ一覧"}%>
    <div class="row">
      <%= search_form_for(@q, url: search_path, html: { method: :get}) do |f| %>
        <div class="input-field inline col s8 offset-s2">
          <%= f.text_field :name_cont, autocomplete: "off"%>
          <%= f.label :name, "レシピ名で検索"%>
        </div>
          <%= button_tag(type: 'submit', class: 'btn-floating btn-large waves-effect waves-light red', form: 'post_search', name: nil) do%>
            <i class="material-icons">search</i>
          <% end %>
      <% end %>
    </div>
    <h3>新着レシピ</h3>
    <div class="row">
      <div class="collection">
        <% @post.each do |p| %>
            <%= link_to p.name, show_post_path(p), class: 'collection-item'%>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/layouts/_footer.html.erb
    <% #snackbar%>
    <% if flash[:notice] %>
      <%= render partial: 'layouts/snackbar', locals: {flash_cat: 'mdl-color--blue-400', msg: flash[:notice]}%>
    <% elsif flash[:error] %>
      <%= render partial: 'layouts/snackbar', locals: {flash_cat: 'mdl-color--red', msg: flash[:error]}%>
    <% end %>
    </main>
</div>
</body>
</html>

app/views/layouts/_head.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8">
    <title>Recipe</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <%= yield :javascipt %>
  </head>
<body>

app/views/layouts/_header.html.erb
<!-- Uses a header that scrolls with the text, rather than staying
  locked at the top -->
<div class="mdl-layout mdl-js-layout">
  <header class="mdl-layout__header mdl-layout__header--scroll">
    <div class="mdl-layout__header-row">
      <!-- Title -->
      <span class="mdl-layout-title"><%= link_to 'Top', root_path, class: 'white-text'%></span>
      <!-- Add spacer, to align navigation to the right -->
      <div class="mdl-layout-spacer"></div>
      <!-- Navigation -->
      <nav class="mdl-navigation">
        <%= link_to 'タグ新規作成', tags_path, class: 'mdl-navigation__link' %>
        <%= link_to '食材新規登録', foodstuffs_path, class: 'mdl-navigation__link' %>
        <%= link_to 'レシピ新規登録', posts_path, class: 'mdl-navigation__link' %>
      </nav>
    </div>
  </header>
  <div class="mdl-layout__drawer">
    <span class="mdl-layout-title"><%= link_to 'Top', root_path, class: 'grey-text' %></span>
    <nav class="mdl-navigation">
      <%= link_to 'タグ新規作成', tags_path, class: 'mdl-navigation__link'%>
      <%= link_to '食材新規登録', foodstuffs_path, class: 'mdl-navigation__link' %>
      <%= link_to 'レシピ新規登録', posts_path, class: 'mdl-navigation__link' %>
    </nav>
  </div>

app/views/layouts/_snackbar.html.erb
<div id="flash" class="mdl-js-snackbar mdl-snackbar <%= flash_cat %>">
  <div class="mdl-snackbar__text text-center"></div>
  <button class="mdl-snackbar__action" type="button" style="display: hidden;"></button>
</div>
<script>
(function() {
  'use strict';
  var snackbarContainer = document.querySelector('#flash');
  window.addEventListener('load', function() {
    setTimeout(function(){
      var data = {
        message: '<%= msg %>',
        timeout: 2000,
      };
      snackbarContainer.MaterialSnackbar.showSnackbar(data);  
    }, 500);
  });
}());
</script>

app/views/layouts/application.html.erb
<%= render 'layouts/head' %>
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>

app/views/post/_foodstuff_amount_form.html.erb
<div class="card-content nested-fields foodstuff_amount_form">
  <div class="input-field col s12 m6">
    <%= f.text_field :foodstuff, autocomplete:'off' %>
    <%= f.label :foodstuff, '食材' %>
  </div>
  <div class="input-field col s12 m5">
    <%= f.text_field :amount, autocomplete:'off' %>
    <%= f.label :amount, '分量（単位あり）' %>
  </div>
  <div class="valign-wrapper col s12 m1">
    <%= link_to_remove_association "削除", f %>
  </div>
</div>

app/views/post/_item_collection.html.erb
<div class="col s12 m6">
  <% if obj.present? %>
    <ul class="collection with-header">
      <li class = "collection-header"><h3><%= obj_name %></h3></li>
    <% obj.each do |f| %>
      <li class="collection-item"><%= f.name %></li>
    <% end %>
    </ul>
  <% else %>
    <p><%= obj_name %></p>
  <% end %>
</div>

app/views/post/_post_form.html.erb
<div class="input-field col s12">
  <%= f.text_field :name, class: 'validate', autocomplete:'off' %>
  <%= f.label :name, '料理名'%>
</div>
<h3>料理の写真</h3>
<div class="file-field input-field col s12">
  <div class="btn">
    <span>ファイル</span>
    <%= f.file_field :image %>
    <%= f.hidden_field :image_cache %>
  </div>
  <div class="file-path-wrapper">
    <% image_cache = @post.image_cache.present? ? File.basename(@post.image_cache) : "" %>
    <%= text_field_tag "", image_cache, class: "file-path validate" %>
    <% if @post.errors[:image].present? %>
      <span><%= @post.errors.full_messages_for(:image).join %></span>
    <% end %>
  </div>
</div>
<div class="input-field col s12">
  <%= f.text_area :description, class: 'materialize-textarea', autocomplete:'off', rows: 10 , style: "height: 150px"%>
  <%= f.label :decription, 'レシピの概要'%>
</div>

app/views/post/_process_form.html.erb
<div class="nested-fields">
  <div class="card col s12">
    <div class="card-content">
      <div class="input-field">
        <%= f.text_field :title, class: 'validate' ,autocomplete:'off'%>
        <%= f.label :title, 'タイトル'%>
      </div>
    </div>
    <div class="card-content">
      <div class="input-field">
        <%= f.text_area :description, class: 'materialize-textarea', autocomplete:'off', style: "height: 100px" %>
        <%= f.label :decription, '工程' %>
      </div>
    </div>
  </div>
  <%= link_to_remove_association "削除", f %>
</div>

app/views/post/index.html.erb
<div class="container post">
  <section>
     <%= render partial: "common/title", locals: {title: "レシピ登録"}%>
  </section>
  <section>
    <div class="row">
      <%= form_for @post, :html => {:class => "col s12"} do |p|%>
      <% if @post.errors.any? %>
      <div id="error_explanation">
        <h2><%= @post.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
          <%= render partial: "post_form", locals: { f: p } %>
        <h3>各食材と分量</h3>
        <div class="row nest">
          <div class="card foodstuff_amount_card col s12">
            <%= p.fields_for :foodstuff_amounts do |foodstuff_amount| %>
              <%= render partial: "foodstuff_amount_form", locals: { f: foodstuff_amount } %>
            <% end %>
            <div class="link foodstuff_amounts">
              <%= link_to_add_association '<i class="material-icons">add</i>'.html_safe, p, :foodstuff_amounts, partial: 'foodstuff_amount_form', class: 'btn-floating btn-large waves-effect waves-light red'%>
            </div>
          </div>
        </div>
        <h3>タグ選択</h3>
        <%= render partial: "common/check_boxes", locals: { f: p, id_name: :tag_ids, object_name: Tag.all } %>
        <h3>食材タグ選択</h3>
        <%= render partial: "common/check_boxes", locals: { f: p, id_name: :foodstuff_ids, object_name: Foodstuff.all } %>
        <h3>工程・手順</h3>
        <div class="row nest">
          <%= p.fields_for :recipe_processes do |recipe_processe| %>
            <%= render partial: "process_form", locals: { f: recipe_processe } %>
          <% end %>
          <div class="link recipe_processes">
            <%= link_to_add_association '<i class="material-icons">add</i>'.html_safe, p, :recipe_processes, partial: 'process_form', class: 'btn-floating btn-large waves-effect waves-light red'%>
          </div>
        </div>
        <%= button_tag(type: 'submit', class: 'waves-effect waves-light btn-large', form: "new_post", name: nil) do%>
          投稿
        <% end %>
      <% end %>
    </div>
  </section>
</div>

app/views/post/show.html.erb
<div class="container">
  <section>
    <%= render partial: "common/title", locals: {title: "レシピ"}%>
    <div class="row">
      <div class="col s12">
        <h2><%= @post.name%></h2>
      </div>
    </div>
    <div class="card row">
      <div class="col s12 m6">
        <%= image_tag @post.image.thumb.url, class: "responsive-img"%>
      </div>
      <div class="col s12 m6">
        <table class="striped centered">
          <thead>
            <tr>
                <th>食材</th>
                <th>分量</th>
            </tr>
          </thead>
          <tbody>
          <% @post.foodstuff_amounts.order(order: "ASC").each do |f|%>
          <tr>
            <td><%= f.foodstuff %></td>
            <td><%= f.amount %></td>
          </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <%= render partial: "item_collection", locals: {obj: @post.tags, obj_name: "タグ"} %>
      <%= render partial: "item_collection", locals: {obj: @post.foodstuffs, obj_name: "食材タグ"} %>
    </div>
    <div class="row">
    <% @post.recipe_processes.order(order: "ASC").each do |process| %>
    <div class="col s12 m3 processe">
      <div class="card">
        <div class="card-content">
          <span class="card-title process__order"><%= process.order %></span>
          <p class="bd__bottom process__title"><%= process.title %></p>
        </div>
        <div class="card-content process__description">
          <p><%= process.description %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>
  </section>
</div>

app/views/search/index.html.erb
<div class="container">
  <section>
    <%= render partial: "common/title", locals: {title: "#{@word[:name_cont]} の検索結果"}%>
    <div class="row">
      <%= search_form_for(@q, url: search_path, html: { method: :get}) do |f| %>
        <div class="input-field inline col s8 offset-s2">
          <%= f.text_field :name_cont, autocomplete: "off"%>
          <%= f.label :name, "レシピ名で検索"%>
        </div>
          <%= button_tag(type: 'submit', class: 'btn-floating btn-large waves-effect waves-light red', form: 'post_search', name: nil) do%>
            <i class="material-icons">search</i>
          <% end %>
      <% end %>
    </div>
    <h3>検索結果</h3>
    <div class="row">
      <div class="collection">
        <% @posts.each do |p| %>
            <%= link_to p.name, show_post_path(p), class: 'collection-item'%>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/tag/index.html.erb
<div class="container">
  <section>
    <%= render partial: "common/title", locals: {title: "タグ作成"}%>
    <%= render partial: "common/new_form", locals: {data: @tag, t_name: 'タグ', f_name: 'tag'}%>
  </section>
  <% if @tags.present? %>
  <section>
    <div class="row">
      <h2 class="center-align">タグ一覧</h2>
    </div>
    <div class="row">
      <ul class="col s6 offset-s3">
        <%= render partial: "common/tag_list", collection: @tags, as: "data" %>
      </ul>
    </div>
  </section>
  <% end %>
</div>